/**
 * Field and option captions of the content registry, translated by field name.
 *
 * Field names in `content-types.ts` follow the database columns, so one entry here covers every
 * material type that uses the same column — which is why adding a content type needs no new strings.
 * Falls back to the English label from the registry when a name is missing here.
 */
import type { AdminLocale } from './labels';

const INDEX: Record<AdminLocale, 0 | 1 | 2> = { ru: 0, en: 1, uz: 2 };

/** [ru, en, uz] */
type Triplet = readonly [string, string, string];

const FIELDS: Record<string, Triplet> = {
  title: ['Заголовок', 'Title', 'Sarlavha'],
  subtitle: ['Подзаголовок', 'Subtitle', 'Qism sarlavha'],
  slug: ['Адрес (slug)', 'URL slug', 'Manzil (slug)'],
  lang: ['Язык версии', 'Language', 'Til'],
  excerpt: ['Краткое описание', 'Short description', 'Qisqacha tavsif'],
  body: ['Основной текст', 'Content', 'Asosiy matn'],
  mainImage: ['Главное изображение', 'Main image', 'Asosiy rasm'],
  gallery: ['Галерея', 'Gallery', 'Galereya'],
  attachments: ['Вложения', 'Attachments', 'Ilovalar'],
  author: ['Автор', 'Author', 'Muallif'],
  status: ['Статус', 'Status', 'Holat'],
  publishedAt: ['Дата публикации', 'Publication date', "E'lon sanasi"],
  tags: ['Теги', 'Tags', 'Teglar'],
  seoTitle: ['SEO заголовок', 'SEO title', 'SEO sarlavhasi'],
  seoDescription: ['SEO описание', 'SEO description', 'SEO tavsifi'],
  keywords: ['Ключевые слова', 'Keywords', 'Kalit so‘zlar'],
  canonicalUrl: ['Канонический адрес', 'Canonical URL', 'Kanonik manzil'],
  ogTitle: ['Заголовок для соцсетей', 'Social share title', 'Ijtimoiy tarmoq sarlavhasi'],
  ogDescription: ['Описание для соцсетей', 'Social share description', 'Ijtimoiy tarmoq tavsifi'],
  ogImage: ['Изображение для соцсетей', 'Social share image', 'Ijtimoiy tarmoq rasmi'],
  noIndex: ['Скрыть от поисковиков', 'Hide from search engines', 'Qidiruv tizimlaridan yashirish'],
  categoryId: ['Рубрика', 'Category', "Bo'lim"],
  eventDate: ['Дата события', 'Event date', 'Tadbir sanasi'],
  isFeatured: ['Показывать на главной', 'Featured', 'Bosh sahifada ko‘rsatish'],
  journalId: ['Журнал', 'Journal', 'Jurnal'],
  doi: ['DOI', 'DOI', 'DOI'],
  references: ['Литература', 'References', 'Adabiyotlar'],
  authors: ['Авторы', 'Authors', 'Mualliflar'],
  isbn: ['ISBN', 'ISBN', 'ISBN'],
  publisher: ['Издательство', 'Publisher', 'Nashriyot'],
  place: ['Место издания', 'Place of publication', 'Nashr qilingan joy'],
  year: ['Год', 'Year', 'Yil'],
  pages: ['Страницы', 'Pages', 'Sahifalar'],
  edition: ['Издание', 'Edition', 'Nashr'],
  cover: ['Обложка', 'Cover', 'Muqova'],
  fullText: ['PDF книги', 'Book PDF', 'Kitob PDF'],
  kind: ['Тип', 'Type', 'Turi'],
  volume: ['Том', 'Volume', 'Jild'],
  issue: ['Выпуск', 'Issue', 'Son'],
  titleOriginal: ['Название оригинала', 'Original title', 'Asl nomi'],
  authorOriginal: ['Автор оригинала', 'Original author', 'Asl muallifi'],
  repositoryId: ['Индекс хранилища', 'Repository ID', 'Xotira indeksi'],
  invNo: ['Инвентарный номер', 'Inventory number', 'Inventar raqami'],
  languageOfText: ['Язык текста', 'Language of text', 'Matn tili'],
  script: ['Письмо', 'Script', 'Yozuv'],
  subject: ['Тема', 'Subject', 'Mavzu'],
  periodLabel: ['Период', 'Period', 'Davr'],
  century: ['Век', 'Century', 'Asr'],
  dateHijri: ['Дата по хиджре', 'Date (Hijri)', 'Hijriy sana'],
  dateGregorian: ['Дата по григорианскому календарю', 'Date (Gregorian)', 'Milodiy sana'],
  folios: ['Листы', 'Folios', 'Varaqalar'],
  dimensions: ['Размеры', 'Dimensions', "O'lchamlari"],
  material: ['Материал', 'Material', 'Materiali'],
  colophon: ['Колофон', 'Colophon', 'Kolofon'],
  incipit: ['Инципит', 'Incipit', 'Inkipo'],
  explicit: ['Эксплицит', 'Explicit', 'Eksplisit'],
  bibliographicInfo: ['Библиографическое описание', 'Bibliographic information', 'Bibliografik tavsif'],
  digitalCopyNote: ['Сведения о цифровой копии', 'Digital copy information', 'Raqamli nusxa haqida'],
  hasDigitalCopy: ['Есть цифровая копия', 'Digital copy available', 'Raqamli nusxa mavjud'],
  digitalFiles: ['Цифровые файлы', 'Digital files', 'Raqamli fayllar'],
  degree: ['Учёная степень', 'Scientific degree', 'Ilmiy daraja'],
  candidateName: ['Соискатель', 'Candidate', "Izlanuvchi"],
  specialtyCode: ['Код специальности', 'Specialty code', 'Mutaxassislik kodi'],
  specialty: ['Специальность', 'Specialty', 'Mutaxassislik'],
  supervisor: ['Научный руководитель', 'Scientific supervisor', 'Ilmiy rahbar'],
  organization: ['Организация', 'Organization', 'Tashkilot'],
  defenseDate: ['Дата защиты', 'Defense date', 'Himoya sanasi'],
  defenseTime: ['Время защиты', 'Defense time', 'Himoya vaqti'],
  defensePlace: ['Место защиты', 'Defense place', 'Himoya joyi'],
  councilCode: ['Код совета', 'Council code', 'Kengash kodi'],
  stage: ['Статус', 'Status', 'Holat'],
  abstract: ['Автореферат', 'Abstract', 'Autoreferat'],
  documents: ['Документы', 'Documents', 'Hujjatlar'],
  startDate: ['Дата начала', 'Start date', 'Boshlanish sanasi'],
  endDate: ['Дата окончания', 'End date', 'Tugash sanasi'],
  startTime: ['Время начала', 'Start time', 'Boshlanish vaqti'],
  endTime: ['Время окончания', 'End time', 'Tugash vaqti'],
  location: ['Место проведения', 'Location', "O'tkazish joyi"],
  venue: ['Зал', 'Venue / hall', 'Zal'],
  organizers: ['Организатор', 'Organizer', 'Tashkilotchi'],
  speakers: ['Докладчики', 'Speakers', "Ma'ruzachilar"],
  program: ['Программа', 'Program', 'Dastur'],
  registrationUrl: ['Ссылка на регистрацию', 'Registration link', "Ro'yxatdan o'tish havolasi"],
  contactPerson: ['Контактное лицо', 'Contact person', 'Aloqa shaxsi'],
  contactEmail: ['Контактный email', 'Contact email', 'Aloqa emaili'],
  contactPhone: ['Контактный телефон', 'Contact phone', 'Aloqa telefoni'],
  isOnline: ['Онлайн', 'Online', 'Onlayn'],
  isInternational: ['Международное', 'International', 'Xalqaro'],
  videos: ['Видео', 'Videos', 'Videolar'],
  expiresAt: ['Действует до', 'Valid until', 'Amal qilish muddati'],
  isPinned: ['Закрепить сверху', 'Pin to top', 'Yuqoriga mahkamlash'],
  position: ['Должность', 'Position', 'Lavozim'],
  leadershipRole: ['Роль в руководстве', 'Leadership role', 'Rahbariyatdagi o‘rni'],
  academicTitle: ['Учёное звание', 'Academic title', 'Ilmiy unvon'],
  interests: ['Научные интересы', 'Research interests', 'Ilmiy qiziqishlar'],
  departmentId: ['Подразделение', 'Department', "Bo'lim"],
  email: ['Email', 'Email', 'Email'],
  phone: ['Телефон', 'Phone', 'Telefon'],
  orcid: ['ORCID', 'ORCID', 'ORCID'],
  website: ['Сайт', 'Website', 'Veb-sayt'],
  links: ['Дополнительные ссылки', 'Additional links', "Qo'shimcha havolalar"],
  birthYear: ['Год рождения', 'Birth year', "Tug'ilgan yili"],
  isYoungScientist: ['Молодой учёный', 'Young scientist', 'Yosh olim'],
  photo: ['Фотография', 'Photograph', 'Foto'],
  publications: ['Публикации', 'Publications', 'Nashrlar'],
  parentId: ['Вышестоящее подразделение', 'Parent unit', 'Yuqori bo‘lim'],
  headResearcherId: ['Руководитель подразделения', 'Head of unit', "Bo'lim rahbari"],
  room: ['Кабинет', 'Room', 'Xona'],
  sortOrder: ['Порядок отображения', 'Display order', 'Ko‘rsatilish tartibi'],
  leadResearcherId: ['Руководитель направления', 'Direction lead', "Yo'nalish rahbari"],
  members: ['Участники', 'Participants', 'Ishtirokchilar'],
  projects: ['Совместные проекты', 'Joint projects', "Qo'shma loyihalar"],
  code: ['Код', 'Code', 'Kodi'],
  directionId: ['Направление исследований', 'Research direction', "Tadqiqot yo'nalishi"],
  fundingSource: ['Источник финансирования', 'Funding source', 'Moliyalashtirish manbai'],
  budget: ['Бюджет', 'Budget', 'Byudjet'],
  startYear: ['Год начала', 'Start year', 'Boshlanish yili'],
  endYear: ['Год окончания', 'End year', 'Tugash yili'],
  country: ['Страна', 'Country', 'Davlat'],
  orgType: ['Тип организации', 'Organization type', 'Tashkilot turi'],
  logo: ['Логотип', 'Logo', 'Logotip'],
  agreementNumber: ['Номер договора', 'Agreement number', 'Shartnoma raqami'],
  signedAt: ['Дата подписания', 'Date signed', 'Imzolangan sana'],
  validFrom: ['Действует с', 'Valid from', 'Amal qilish boshi'],
  validTo: ['Действует по', 'Valid to', 'Amal qilish tugashi'],
  isActive: ['Активное партнёрство', 'Active partnership', 'Faol hamkorlik'],
  docNumber: ['Номер документа', 'Document number', 'Hujjat raqami'],
  issuedAt: ['Дата выдачи', 'Issue date', 'Berilgan sanasi'],
  file: ['Файл', 'File', 'Fayl'],
  template: ['Шаблон страницы', 'Template', 'Sahifa shabloni'],
  pathOverride: ['Путь в адресной строке', 'URL path', 'URL yo‘li'],
  showInBreadcrumbs: ['Показывать в цепочке разделов', 'Show in breadcrumbs', "Bo'limlar zanjirida ko‘rsatish"],
  issn: ['ISSN', 'ISSN', 'ISSN'],
  eissn: ['eISSN', 'eISSN', 'eISSN'],
  foundedYear: ['Год основания', 'Founded year', 'Asoslangan yili'],
};

const OPTIONS: Record<string, Triplet> = {
  none: ['Не выбрано', 'None', 'Tanlanmagan'],
  book: ['Книга', 'Book', 'Kitob'],
  article: ['Статья', 'Article', 'Maqola'],
  journal: ['Научный журнал', 'Scientific journal', 'Ilmiy jurnal'],
  proceedings: ['Труды конференции', 'Conference proceedings', 'Konferensiya to‘plami'],
  dissertation: ['Диссертация', 'Dissertation', 'Dissertatsiya'],
  report: ['Отчёт', 'Report', 'Hisobot'],
  other: ['Другое', 'Other', 'Boshqa'],
  phd: ['PhD (кандидатская)', 'PhD', 'PhD'],
  dsc: ['DSc (докторская)', 'DSc', 'DSc'],
  announced: ['Объявлена', 'Announced', "E'lon qilingan"],
  defended: ['Защищена', 'Defended', 'Himoya qilingan'],
  awarded: ['Степень присуждена', 'Awarded', 'Daraja berilgan'],
  withdrawn: ['Отозвана', 'Withdrawn', 'Bekor qilingan'],
  conference: ['Конференция', 'Conference', 'Konferensiya'],
  seminar: ['Семинар', 'Seminar', 'Seminar'],
  workshop: ['Практикум', 'Workshop', 'Vorkshop'],
  scientific_meeting: ['Научное заседание', 'Scientific meeting', 'Ilmiy kengash'],
  summer_school: ['Летняя школа', 'Summer school', 'Yozgi maktab'],
  public_lecture: ['Публичная лекция', 'Public lecture', "Ommaviy ma'ruza"],
  international: ['Международное событие', 'International event', 'Xalqaro tadbir'],
  scientific: ['Научные объявления', 'Scientific announcements', 'Ilmiy e’lonlar'],
  vacancy: ['Вакансии', 'Vacancies', 'Vakansiyalar'],
  procurement: ['Закупки', 'Procurement', 'Xaridlar'],
  event: ['Мероприятия', 'Events', 'Tadbirlar'],
  official: ['Официальные', 'Official', 'Rasmiy'],
  regulation: ['Положение', 'Regulation', 'Lowa'],
  order: ['Приказ', 'Order', 'Buyruq'],
  conference_program: ['Программа конференции', 'Conference program', 'Konferensiya dasturi'],
  director: ['Директор', 'Director', 'Direktor'],
  deputy_director: ['Заместитель директора', 'Deputy director', 'Direktor o‘rinbosari'],
  scientific_secretary: ['Учёный секретарь', 'Scientific secretary', 'Ilmiy kotib'],
  department_head: ['Заведующий отделом', 'Department head', "Bo'lim mudiri"],
  department: ['Отдел', 'Department', "Bo'lim"],
  center: ['Научный центр', 'Research center', 'Ilmiy markaz'],
  group: ['Научная группа', 'Research group', 'Ilmiy guruh'],
  council: ['Учёный совет', 'Scientific council', 'Ilmiy kengash'],
  division: ['Подразделение', 'Division', 'Bo‘linma'],
  laboratory: ['Лаборатория', 'Laboratory', 'Laboratoriya'],
  planned: ['Запланирован', 'Planned', 'Rejalashtirilgan'],
  active: ['Активен', 'Active', 'Faol'],
  completed: ['Завершён', 'Completed', 'Yakunlangan'],
  cancelled: ['Остановлен', 'Cancelled', 'To‘xtatilgan'],
  university: ['Университет', 'University', 'Universitet'],
  research_institute: ['Научно-исследовательский институт', 'Research institute', 'Ilmiy tadqiqot instituti'],
  museum: ['Музей', 'Museum', 'Muzey'],
  archive: ['Архив', 'Archive', 'Arxiv'],
  ngo: ['Некоммерческая организация', 'NGO', 'Notijorat tashkilot'],
  government: ['Государственный орган', 'Government body', 'Davlat organ'],
  standard: ['Обычная страница', 'Standard', 'Oddiy sahifa'],
  landing: ['Посадочная страница', 'Landing', 'Landing sahifa'],
  full_width: ['Во всю ширину', 'Full width', "To'liq kenglikda"],
  sidebar: ['С боковой колонкой', 'With sidebar', 'Yon ustun bilan'],
};

export function fieldLabel(locale: AdminLocale, name: string, fallback?: string): string {
  const entry = FIELDS[name];
  return entry ? entry[INDEX[locale]] : (fallback ?? name);
}

/** Tooltips under a field. Anything not listed here keeps the English hint from the registry. */
const HINTS: Record<string, Triplet> = {
  slug: ['Латиница и дефисы. При изменении адреса старый автоматически перенаправляется на новый.', 'Latin letters and hyphens. Changing the address creates a redirect from the old one.', 'Lotin harflari va defis. Manzil oʻzgartirilsa, eski manzil yangiga yoʻnaltiriladi.'],
  body: ['Изображения вставляйте из медиатеки, а не набирая путь вручную.', 'Insert images from the Media Library instead of typing a path.', 'Rasmlarni qoʻlda yozmang — media kutubxonadan tanlang.'],
  excerpt: ['Показывается в списках и поиске. Лучше до 300 символов.', 'Shown in listings and search results. Keep it under 300 characters.', 'Roʻyxat va qidiruvda koʻrinadi. 300 belgidan oshirmasligi yaxshi.'],
  references: ['Каждая ссылка — с новой строки.', 'One reference per line.', 'Har bir manba — yangi qatordan.'],
  tags: ['Теги через запятую. Новые теги создаются автоматически.', 'Separate tags with commas. New tags are created automatically.', 'Teglarni vergul bilan ajrating. Yangi teglar avtomatik yaratiladi.'],
  mainImage: ['Выбирайте изображение из медиатеки, а не вставляйте путь вручную.', 'Pick the image from the Media Library instead of typing a path.', 'Manzilni qoʻlda yozmang, media kutubxonadan tanlang.'],
  attachments: ['PDF, DOCX, XLSX. Файл можно заменить позже — ссылка на материал останется прежней.', 'PDF, DOCX, XLSX. A file can be replaced later without changing the address of the material.', 'PDF, DOCX, XLSX. Faylni keyin almashtirsangiz — material manzili oʻzgarmaydi.'],
  file: ['PDF, DOCX или XLSX. Замена файла сохраняет ту же ссылку для скачивания.', 'PDF, DOCX or XLSX. Replacing the file keeps the same download link.', 'PDF, DOCX yoki XLSX. Faylni almashtirsangiz, havola oʻzgarmaydi.'],
  documents: ['Автореферат, полный текст, протокол, отзывы.', 'Author abstract, full text, protocol, reviews.', 'Autoreferat, toʻliq matn, protokol, fikrlar.'],
  videos: ['Ссылка на YouTube или Vimeo либо загруженный ролик.', 'A YouTube or Vimeo address, or an uploaded video.', 'YouTube yoki Vimeo manzili yoki yuklangan video.'],
  seoTitle: ['Рекомендуемая длина: 50–60 символов.', 'Recommended length: 50–60 characters.', 'Tavsiya etilgan uzunlik: 50–60 belgi.'],
  seoDescription: ['Рекомендуемая длина: 120–160 символов.', 'Recommended length: 120–160 characters.', 'Tavsiya etilgan uzunlik: 120–160 belgi.'],
  repositoryId: ['Шифр или номер фонда, в котором хранится рукопись.', 'Signature or inventory number of the manuscript fund.', 'Qoʻlyozma saqlanadigan fond raqami yoki shifri.'],
  invNo: ['Инвентарный номер в хранилище.', 'Inventory number in the fund.', 'Xotiradagi inventar raqami.'],
  languageOfText: ['Язык, на котором написана рукопись, а не язык каталога.', 'The language the manuscript is written in, not the catalogue language.', "Qo'lyozma yozilgan til, katalog tili emas."],
  parentId: ['Используется для схемы структуры института.', 'Used to draw the institute organigram.', 'Institut tuzilma sxemasi uchun ishlatiladi.'],
  links: ['По одной ссылке в строке: «Название | https://example.com».', 'One link per line as “Label | https://example.com”.', 'Har satrda bitta havola: «Nomi | https://example.com».'],
  expiresAt: ['После этой даты объявление автоматически скрывается с сайта.', 'After this date the announcement is hidden from the site automatically.', 'Bu sanadan keyin e’lon saytdan avtomatik yashiriladi.'],
  leadershipRole: ['Показывается на странице «Руководство».', 'Shown on the Leadership page.', '«Rahbariyat» sahifasida ko‘rsatiladi.'],
  lang: ['Версия материала на одном языке. Остальные языки — в разделе «Переводы».', 'This version is in one language. Other languages are managed in Translations.', 'Bu versiya bitta tilda. Qolgan tillar «Tarjimalar» boʻlimida.'],
  author: ['Сотрудник института, чьим именем подписан материал.', 'The institute staff member credited with this material.', 'Materialga nomidan eʼlon qilingan institut xodimi.'],
};

export function fieldHint(locale: AdminLocale, name: string): string | null {
  const entry = HINTS[name];
  return entry ? entry[INDEX[locale]] : null;
}

export function optionLabel(locale: AdminLocale, value: string, fallback: string): string {
  const entry = OPTIONS[value];
  return entry ? entry[INDEX[locale]] : fallback;
}
